local huntingLocations = Harmony.ui.side.top.addButton("walkToHunting", "Hunting")

local huntingLevel1 = Harmony.ui.side.top.addChildFlyout(huntingLocations, "hunting1k", "1000+")
huntingLevel1:setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel1, "actarValleyHunting", "Actar Valley", "mmp.gotoRoom", 12066):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel1, "bopalopiaHunting", "Bopalopia", "mmp.gotoRoom", 23021):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel1, "beastlordHunting", "Beastlords", "mmp.gotoRoom", 4230):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel1, "bogOfAshtanHunting", "Bog of Ashtan", "mmp.gotoRoom", 10266):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel1, "manara1Hunting", "Manara F1", "mmp.gotoRoom", 16349):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel1, "manara2Hunting", "Manara F2", "mmp.gotoRoom", 18316):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel1, "mhojaveDesert", "Mhojave Desert", "mmp.gotoRoom", 328):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel1, "tasurkeCavesHunting", "Tasur'ke Caves", "mmp.gotoRoom", 18560):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel1, "hxaidenDaleHunting", "Xhaiden Dale (Lower)", "mmp.gotoRoom", 26420):setStyleSheet(Harmony.ui.styles.huntingButton)

local huntingLevel2 = Harmony.ui.side.top.addChildFlyout(huntingLocations, "hunting2k", "2000+")
huntingLevel2:setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "aeraithianFallsHunting", "Aeraithian Falls", "mmp.gotoRoom", 11027):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "aranroidHunting", "Aran'roid (W - NW)", "mmp.gotoRoom", 7584):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "azdunFloor1Hunting", "Azdun F1", "mmp.gotoRoom", 1772):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "beastlordsOphidianHunting", "Beaslords", "mmp.gotoRoom", 4277):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "blackForestHunting", "Black Forest", "mmp.gotoRoom", 23544):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "enverrenCastleHunting", "Enverren Castle", "mmp.gotoRoom", 17865):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "enverrenMarshHunting", "Enverren Marsh", "mmp.gotoRoom", 19239):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "dunValleyCavemenHunting", "Dun Valley Cavemen", "mmp.gotoRoom", 4695):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "dunFortressEntranceHunting", "Dun Fortress Entrance", "mmp.gotoRoom", 3886):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "dwarvenCampHunting", "Dwarven Camp", "mmp.gotoRoom", 10837):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "forestWatchHunting", "Forest Watch", "mmp.gotoRoom", 7694):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "goblinVillageHunting", "Goblin Village", "mmp.gotoRoom", 6625):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "greenLakeHunting", "Green Lake", "mmp.gotoRoom", 8328):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "jaruHunting", "Jaru (Targossas)", "mmp.gotoRoom", 5587):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "kamleikanHunting", "Kamleikan (W - NW)", "mmp.gotoRoom", 7584):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "lakeMuurnHunting", "Lake Muurn", "mmp.gotoRoom", 9567):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "manara3Hunting", "Manara F3", "mmp.gotoRoom", 16490):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "manticoresUpperHunting", "Manticore (Upper)", "mmp.gotoRoom", 10129):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "manushaHunting", "Manusha", "mmp.gotoRoom", 8729):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "northReachHunting", "Northreach", "mmp.gotoRoom", 7367):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "orcCampHunting", "Orc Camp", "mmp.gotoRoom", 10865):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "polyargosHunting", "Polyargos (F)", "mmp.gotoRoom", 6557):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "rheodadHunting", "Rheodad (W - West)", "mmp.gotoRoom", 7537):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "sangrePlainsHunting", "Sangre Plains", "mmp.gotoRoom", 7626):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "shalaKhuliaHunting", "Shala-Khulia (F)", "mmp.gotoRoom", 6557):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "shalajenHunting", "Shala'jen", "mmp.gotoRoom", 7060):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "ulangiHunting", "Ulangi (F)", "mmp.gotoRoom", 2864):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "undergroundLakeHunting", "Underground Lake", "mmp.gotoRoom", 8609):setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel2, "xhaidenDalteUpperHunting", "Xhaden Dale", "mmp.gotoRoom", 24954):setStyleSheet(Harmony.ui.styles.huntingButton)

local huntingLevel3 = Harmony.ui.side.top.addChildFlyout(huntingLocations, "hunting3k", "3000+")
huntingLevel3:setStyleSheet(Harmony.ui.styles.huntingButton)
Harmony.ui.side.top.addFlyoutChild(huntingLevel3, "crevilleHunting", "Creville Asylum", "mmp.gotoRoom", 26220):setStyleSheet(Harmony.ui.styles.huntingButton)