local sapienceLocations = Harmony.ui.side.top.addButton("walkToSapience", "Sapience")
local meropisLocations = Harmony.ui.side.top.addButton("walkToMeropis", "Meropis")

local eleusisLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "eleusisFlyout", "Eleusis")
eleusisLocations:setStyleSheet(Harmony.ui.styles.cityEleusis)
local delosLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "delosFlyout", "Delos")
delosLocations:setStyleSheet(Harmony.ui.styles.cityDelos)
local cyreneLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "cyreneFlyout", "Cyrene")
cyreneLocations:setStyleSheet(Harmony.ui.styles.cityCyrene)
local ashtanLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "ashtanFlyout", "Ashtan")
ashtanLocations:setStyleSheet(Harmony.ui.styles.cityAshtan)
local hashanLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "hashanFlyout", "Hashan")
hashanLocations:setStyleSheet(Harmony.ui.styles.cityHashan)
local targossasLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "targossasFlyout", "Targossas")
targossasLocations:setStyleSheet(Harmony.ui.styles.cityTargossas)
local mhaldorLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "mhaldorFlyout", "Mhaldor")
mhaldorLocations:setStyleSheet(Harmony.ui.styles.cityMhaldor)

Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisAtop", "Atop", "mmp.gotoRoom", 6739):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisArena", "Arena", "mmp.gotoRoom", 11158):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisBait", "Bait", "mmp.gotoRoom", 19310):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisBank", "Bank", "mmp.gotoRoom", 8196):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisCauldron", "Cauldron", "mmp.gotoRoom", 6765):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisForge", "Forge", "mmp.gotoRoom", 13160):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisLibrary", "Library", "mmp.gotoRoom", 6751):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisNews", "News", "mmp.gotoRoom", 6799):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisSubdivision", "Subdivision", "mmp.gotoRoom", 6760):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisTutor", "Tutor", "mmp.gotoRoom", 8200):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisWings", "Wings", "mmp.gotoRoom", 5692):setStyleSheet(Harmony.ui.styles.cityEleusis)

Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosArena", "Arena", "mmp.gotoRoom", 2461):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosArtefact", "Artefacts", "mmp.gotoRoom", 10160):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosBank", "Bank", "mmp.gotoRoom", 38931):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosBloodlines", "Bloodlines", "mmp.gotoRoom", 11773):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosCommodities", "Commodities", "mmp.gotoRoom", 44519):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosCrafters", "Crafters", "mmp.gotoRoom", 8431):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosNews", "News", "mmp.gotoRoom", 10010):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosPost", "Post", "mmp.gotoRoom", 20317):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosProperty", "Property", "mmp.gotoRoom", 8124):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosWings", "Wings", "mmp.gotoRoom", 1180):setStyleSheet(Harmony.ui.styles.cityDelos)

Harmony.ui.side.top.addFlyoutChild(mhaldorLocations, "mhaldorWings", "Wings", "mmp.gotoRoom", 10583):setStyleSheet(Harmony.ui.styles.cityMhaldor)