local sapienceLocations = Harmony.ui.side.top.addButton("walkToSapience", "Sapience")
local meropisLocations = Harmony.ui.side.top.addButton("walkToMeropis", "Meropis")

local eleusisLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "eleusisFlyout", "Eleusis", 6739)
eleusisLocations:setStyleSheet(Harmony.ui.styles.cityEleusis)
local delosLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "delosFlyout", "Delos", 1181)
delosLocations:setStyleSheet(Harmony.ui.styles.cityDelos)
local cyreneLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "cyreneFlyout", "Cyrene", 6298)
cyreneLocations:setStyleSheet(Harmony.ui.styles.cityCyrene)
local ashtanLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "ashtanFlyout", "Ashtan", 436)
ashtanLocations:setStyleSheet(Harmony.ui.styles.cityAshtan)
local hashanLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "hashanFlyout", "Hashan", 4472)
hashanLocations:setStyleSheet(Harmony.ui.styles.cityHashan)
local targossasLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "targossasFlyout", "Targossas", 40513)
targossasLocations:setStyleSheet(Harmony.ui.styles.cityTargossas)
local mhaldorLocations = Harmony.ui.side.top.addChildFlyout(sapienceLocations, "mhaldorFlyout", "Mhaldor")
mhaldorLocations:setStyleSheet(Harmony.ui.styles.cityMhaldor)

Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisAtop", "Atop", "mmp.gotoRoom", 6739):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisArena", "Arena", "mmp.gotoRoom", 11158):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisBait", "Bait", "mmp.gotoRoom", 19310):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisBank", "Bank", "mmp.gotoRoom", 8196):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisCauldron", "Cauldron", "mmp.gotoRoom", 6765):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisForge", "Forge", "mmp.gotoRoom", 13160):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisGates", "Gates", "mmp.gotoRoom", 6738):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisLibrary", "Library", "mmp.gotoRoom", 6751):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisNews", "News", "mmp.gotoRoom", 6799):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisPost", "Post", "mmp.gotoRoom", 8197):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisRestaurant", "Restaurant", "mmp.gotoRoom", 15123):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisStables", "Stables", "mmp.gotoRoom", 42090):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisSubdivision", "Subdivision", "mmp.gotoRoom", 6760):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisTemple", "Temple", "mmp.gotoRoom", 2377):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisTutor", "Tutor", "mmp.gotoRoom", 8200):setStyleSheet(Harmony.ui.styles.cityEleusis)
Harmony.ui.side.top.addFlyoutChild(eleusisLocations, "eleusisWings", "Wings", "mmp.gotoRoom", 5692):setStyleSheet(Harmony.ui.styles.cityEleusis)

Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosArena", "Arena", "mmp.gotoRoom", 2461):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosArtefact", "Artefacts", "mmp.gotoRoom", 32003):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosBank", "Bank", "mmp.gotoRoom", 38931):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosBloodlines", "Bloodlines", "mmp.gotoRoom", 11773):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosBridge", "Bridge", "mmp.gotoRoom", 1181):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosCertimene", "Certimene", "mmp.gotoRoom", 8660):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosClans", "Clans", "mmp.gotoRoom", 5423):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosCommodities", "Commodities", "mmp.gotoRoom", 44519):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosCrafters", "Crafters", "mmp.gotoRoom", 8431):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosEstate", "Estate", "mmp.gotoRoom", 1186):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosHumgii", "Humgii", "mmp.gotoRoom", 36013):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosNews", "News", "mmp.gotoRoom", 10010):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosPost", "Post", "mmp.gotoRoom", 20317):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosProperty", "Property", "mmp.gotoRoom", 8124):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosTattoos", "Tattoos", "mmp.gotoRoom", 2540):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosTheatre", "Theatre", "mmp.gotoRoom", 32183):setStyleSheet(Harmony.ui.styles.cityDelos)
Harmony.ui.side.top.addFlyoutChild(delosLocations, "delosWings", "Wings", "mmp.gotoRoom", 1180):setStyleSheet(Harmony.ui.styles.cityDelos)

Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneArena", "Arena", "mmp.gotoRoom", 12983):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneArtistan", "Artisan Plaza", "mmp.gotoRoom", 6301):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneBank", "Bank", "mmp.gotoRoom", 6311):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneCafe", "Cafe", "mmp.gotoRoom", 6544):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneCentre", "Centre", "mmp.gotoRoom", 6298):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneForge", "Forge", "mmp.gotoRoom", 6478):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneGates", "Gates", "mmp.gotoRoom", 6294):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneHumgii", "Humgii", "mmp.gotoRoom", 18691):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneImperium", "Imperium", "mmp.gotoRoom", 6387):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneLaboratory", "Laboratory", "mmp.gotoRoom", 3751):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneNews", "News", "mmp.gotoRoom", 6424):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyrenePost", "Post", "mmp.gotoRoom", 6310):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneRats", "Rats", "mmp.gotoRoom", 6308):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneStables", "Stables", "mmp.gotoRoom", 7100):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneSubdivision", "Subdivision", "mmp.gotoRoom", 6341):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneTemple", "Temple", "mmp.gotoRoom", 7300):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneTutor", "Tutor", "mmp.gotoRoom", 6473):setStyleSheet(Harmony.ui.styles.cityCyrene)
Harmony.ui.side.top.addFlyoutChild(cyreneLocations, "cyreneWings", "Wings", "mmp.gotoRoom", 9559):setStyleSheet(Harmony.ui.styles.cityCyrene)

Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanArena", "Arena", "mmp.gotoRoom", 8822):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanBank", "Bank", "mmp.gotoRoom", 3761):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanCasino", "Casino", "mmp.gotoRoom", 605):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanForge", "Forge", "mmp.gotoRoom", 2046):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanGates", "Gates", "mmp.gotoRoom", 436):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanHumgii", "Humgii", "mmp.gotoRoom", 455):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanLaboratory", "Laboratory", "mmp.gotoRoom", 38229):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanMarket", "Market", "mmp.gotoRoom", 455):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanNews", "News", "mmp.gotoRoom", 10009):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanPalace", "Palace", "mmp.gotoRoom", 35339):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanPost", "Post", "mmp.gotoRoom", 2159):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanRats", "Rats", "mmp.gotoRoom", 531):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanRestuarant", "Restuarant", "mmp.gotoRoom", 11930):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanStables", "Stables", "mmp.gotoRoom", 29920):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanSubdivision", "Subdivision", "mmp.gotoRoom", 436):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanTemple", "Temple", "mmp.gotoRoom", 1526):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanTutor", "Tutor", "mmp.gotoRoom", 496):setStyleSheet(Harmony.ui.styles.cityAshtan)
Harmony.ui.side.top.addFlyoutChild(ashtanLocations, "ashtanWings", "Wings", "mmp.gotoRoom", 1285):setStyleSheet(Harmony.ui.styles.cityAshtan)

Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanAlehouse", "Alehouse", "mmp.gotoRoom", 6879):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanArena", "Arena", "mmp.gotoRoom", 9434):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanBank", "Bank", "mmp.gotoRoom", 4399):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanCourt", "Court", "mmp.gotoRoom", 5512):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanForge", "Forge", "mmp.gotoRoom", 4674):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanFounders", "Founders", "mmp.gotoRoom", 4655):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanGates", "Gates", "mmp.gotoRoom", 4482):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanHumgii", "Humgii", "mmp.gotoRoom", 4472):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanLaboratory", "Laboratory", "mmp.gotoRoom", 32864):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanLibrary", "Library", "mmp.gotoRoom", 5924):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanMarket", "Market", "mmp.gotoRoom", 4547):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanNews", "News", "mmp.gotoRoom", 4564):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanPost", "Post", "mmp.gotoRoom", 4405):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanRats", "Rats", "mmp.gotoRoom", 1384):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanSpiritshrine", "Spiritshrine", "mmp.gotoRoom", 2128):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanStables", "Stables", "mmp.gotoRoom", 4473):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanSubdivision", "Subdivision", "mmp.gotoRoom", 4472):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanTutor", "Tutor", "mmp.gotoRoom", 4606):setStyleSheet(Harmony.ui.styles.cityHashan)
Harmony.ui.side.top.addFlyoutChild(hashanLocations, "hashanWings", "Wings", "mmp.gotoRoom", 4088):setStyleSheet(Harmony.ui.styles.cityHashan)

Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasArena", "Arena", "mmp.gotoRoom", 41653):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasBank", "Bank", "mmp.gotoRoom", 40620):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasForge", "Forge", "mmp.gotoRoom", 2353):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasGates", "Gates", "mmp.gotoRoom", 39635):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasHumgii", "Humgii", "mmp.gotoRoom", 40513):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasLaboratory", "Laboratory", "mmp.gotoRoom", 40779):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasLibrary", "Library", "mmp.gotoRoom", 41351):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasMarket", "Market", "mmp.gotoRoom", 40824):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasNews", "News", "mmp.gotoRoom", 40327):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasPost", "Post", "mmp.gotoRoom", 40190):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasRats", "Rats", "mmp.gotoRoom", 40737):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasRestaurant", "Restaurant", "mmp.gotoRoom", 40042):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasStables", "Stables", "mmp.gotoRoom", 40511):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasSubdivision", "Subdivision", "mmp.gotoRoom", 41574):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasTutor", "Tutor", "mmp.gotoRoom", 14973):setStyleSheet(Harmony.ui.styles.cityTargossas)
Harmony.ui.side.top.addFlyoutChild(targossasLocations, "targossasWings", "Wings", "mmp.gotoRoom", 40411):setStyleSheet(Harmony.ui.styles.cityTargossas)

Harmony.ui.side.top.addFlyoutChild(mhaldorLocations, "mhaldorWings", "Wings", "mmp.gotoRoom", 10583):setStyleSheet(Harmony.ui.styles.cityMhaldor)